---
title: "Literate Programming with Quarto"
author: "Katherine Martini"
date: "02/26/2025"
format: revealjs
theme: solarized
transition: fade
---
# Introduction

- Using World Development Indicators dataset
- Focusing specifically on GDP per capita, Life Expectancy, and Unemployment Rates
- Data for the year 2022

# Summary Statistics

```{python}
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/Users/KathMartini/Desktop/qtm350/wdi.csv')

selected_col = ['gdp_per_capita','life_expectancy', 'unemployment_rate']

summary_table = df[selected_col].describe().T

summary_table = summary_table[["mean", "std", "min", "25%", "50%", "75%", "max"]]
summary_table.columns = ["Mean", "Std Dev", "Min", "25th Percentile", "Median", "75th Percentile", "Max"]

display(summary_table)
```

# Life Expectancy vs GDP per Capita
```{python, echo=FALSE}
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/Users/KathMartini/Desktop/qtm350/wdi.csv')

plt.figure(figsize=(8, 5))
plt.scatter(df["gdp_per_capita"], df["life_expectancy"], alpha=0.7)
plt.xlabel("GDP per Capita")
plt.ylabel("Life Expectancy (Years)")
plt.title("Life Expectancy vs GDP Per Capita")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()
```

# Distribution of Countries with GDP per Capita
```{python}
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/Users/KathMartini/Desktop/qtm350/wdi.csv')

plt.figure(figsize=(8, 5))
plt.hist(df["gdp_per_capita"].dropna(), bins=30, edgecolor="black")
plt.xlabel("GDP per Capita")
plt.ylabel("Number of Countries")
plt.title("Distribution of GDP per Capita (2022)")
plt.show()
```

# Analysis 

The summary statistics show various things, but one to note is the GDP per capita and its high standard deviation. This shows that this variation between countries and their wealth disparities. What this tells us is that there some countries that are very wealthy and very poor, and this variation is shown through the high standard deviation. The figures show a similar story of a moderate to high correlation between higher life expectancies and higher GDP per capita. 

# Thank you for watching this presentation!
